apiVersion: v1
kind: Service
metadata:
  name: jekyll-node-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30097